/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author asus
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        KeluarBtn = new javax.swing.JButton();
        InfoBtn = new javax.swing.JButton();
        TransferBtn1 = new javax.swing.JButton();
        Setorbtn = new javax.swing.JButton();
        TarikBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(0, 0, 255));
        panel1.setLayout(null);

        KeluarBtn.setBackground(new java.awt.Color(0, 0, 255));
        KeluarBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        KeluarBtn.setForeground(new java.awt.Color(255, 255, 255));
        KeluarBtn.setText("Keluar");
        KeluarBtn.setToolTipText("");
        KeluarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarBtnActionPerformed(evt);
            }
        });
        panel1.add(KeluarBtn);
        KeluarBtn.setBounds(550, 390, 180, 60);

        InfoBtn.setBackground(new java.awt.Color(0, 0, 255));
        InfoBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        InfoBtn.setText("Informasi Saldo");
        InfoBtn.setToolTipText("");
        InfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBtnActionPerformed(evt);
            }
        });
        panel1.add(InfoBtn);
        InfoBtn.setBounds(40, 270, 180, 60);

        TransferBtn1.setBackground(new java.awt.Color(0, 0, 255));
        TransferBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TransferBtn1.setForeground(new java.awt.Color(255, 255, 255));
        TransferBtn1.setText("Transfer");
        TransferBtn1.setToolTipText("");
        TransferBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferBtn1ActionPerformed(evt);
            }
        });
        panel1.add(TransferBtn1);
        TransferBtn1.setBounds(40, 390, 180, 60);

        Setorbtn.setBackground(new java.awt.Color(0, 0, 255));
        Setorbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Setorbtn.setForeground(new java.awt.Color(255, 255, 255));
        Setorbtn.setText("Setor Tunai");
        Setorbtn.setToolTipText("");
        Setorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetorbtnActionPerformed(evt);
            }
        });
        panel1.add(Setorbtn);
        Setorbtn.setBounds(550, 270, 180, 70);

        TarikBtn.setBackground(new java.awt.Color(0, 0, 255));
        TarikBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TarikBtn.setForeground(new java.awt.Color(255, 255, 255));
        TarikBtn.setText("Tarik Tunai");
        TarikBtn.setToolTipText("");
        TarikBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarikBtnActionPerformed(evt);
            }
        });
        panel1.add(TarikBtn);
        TarikBtn.setBounds(550, 160, 180, 60);

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel1.add(jButton3);
        jButton3.setBounds(40, 160, 170, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Jenis Transaksi");
        panel1.add(jLabel1);
        jLabel1.setBounds(310, 110, 170, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bank COZY");
        panel1.add(jLabel2);
        jLabel2.setBounds(300, 30, 170, 37);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KeluarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KeluarBtnActionPerformed

    private void InfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBtnActionPerformed
        // TODO add your handling code here:
        new InformasiSaldo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InfoBtnActionPerformed

    private void TransferBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferBtn1ActionPerformed
        // TODO add your handling code here:
        new Transfer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TransferBtn1ActionPerformed

    private void SetorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetorbtnActionPerformed
        // TODO add your handling code here:
        new Setor().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SetorbtnActionPerformed

    private void TarikBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarikBtnActionPerformed
        // TODO add your handling code here:
        new Tarik().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TarikBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Atm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoBtn;
    private javax.swing.JButton KeluarBtn;
    private javax.swing.JButton Setorbtn;
    private javax.swing.JButton TarikBtn;
    private javax.swing.JButton TransferBtn1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
