/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author asus
 */
public class InformasiSaldo extends javax.swing.JFrame {

    /**
     * Creates new form InformasiSaldo
     */
    public InformasiSaldo() {
        initComponents();
        InformasiSaldoModel saldo = new  InformasiSaldoModel();
        SaldoLbl.setText("Rp "+saldo.getSaldo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        SaldoLbl = new javax.swing.JLabel();
        InfoLBL = new javax.swing.JLabel();
        TransaksiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(0, 0, 255));
        panel1.setLayout(null);

        SaldoLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SaldoLbl.setForeground(new java.awt.Color(255, 255, 255));
        SaldoLbl.setText("Rp.");
        panel1.add(SaldoLbl);
        SaldoLbl.setBounds(280, 200, 280, 40);

        InfoLBL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        InfoLBL.setForeground(new java.awt.Color(255, 255, 255));
        InfoLBL.setText("Informasi saldo anda");
        panel1.add(InfoLBL);
        InfoLBL.setBounds(260, 110, 280, 40);

        TransaksiBtn.setBackground(new java.awt.Color(0, 0, 255));
        TransaksiBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TransaksiBtn.setForeground(new java.awt.Color(255, 255, 255));
        TransaksiBtn.setText("Transaksi Lain");
        TransaksiBtn.setToolTipText("");
        TransaksiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiBtnActionPerformed(evt);
            }
        });
        panel1.add(TransaksiBtn);
        TransaksiBtn.setBounds(580, 390, 170, 50);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TransaksiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiBtnActionPerformed
        // TODO add your handling code here:
        new Atm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TransaksiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformasiSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformasiSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformasiSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformasiSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformasiSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoLBL;
    private javax.swing.JLabel SaldoLbl;
    private javax.swing.JButton TransaksiBtn;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
