/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author asus
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form InformasiSaldo
     */
    public Transfer() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        TransaksiBtn = new javax.swing.JButton();
        TransaksiBtn1 = new javax.swing.JButton();
        sisa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jumtransfer1 = new javax.swing.JTextField();
        norek = new javax.swing.JTextField();
        jumtransfer2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(0, 0, 255));
        panel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan No Rekening:");
        panel1.add(jLabel2);
        jLabel2.setBounds(240, 120, 280, 20);
        jLabel2.getAccessibleContext().setAccessibleName("Masukkan Jumlah Transfer");

        TransaksiBtn.setBackground(new java.awt.Color(0, 0, 255));
        TransaksiBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TransaksiBtn.setForeground(new java.awt.Color(255, 255, 255));
        TransaksiBtn.setText("Salah");
        TransaksiBtn.setToolTipText("");
        TransaksiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiBtnActionPerformed(evt);
            }
        });
        panel1.add(TransaksiBtn);
        TransaksiBtn.setBounds(590, 400, 140, 40);

        TransaksiBtn1.setBackground(new java.awt.Color(0, 0, 255));
        TransaksiBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TransaksiBtn1.setForeground(new java.awt.Color(255, 255, 255));
        TransaksiBtn1.setText("Benar");
        TransaksiBtn1.setToolTipText("");
        TransaksiBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiBtn1ActionPerformed(evt);
            }
        });
        panel1.add(TransaksiBtn1);
        TransaksiBtn1.setBounds(590, 320, 140, 40);

        sisa.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sisa.setForeground(new java.awt.Color(255, 255, 255));
        sisa.setText("Sisa Saldo anda:");
        sisa.setToolTipText("");
        panel1.add(sisa);
        sisa.setBounds(40, 340, 420, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Masukkan Jumlah Transfer");
        panel1.add(jLabel4);
        jLabel4.setBounds(240, 230, 280, 20);

        jumtransfer1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jumtransfer1InputMethodTextChanged(evt);
            }
        });
        panel1.add(jumtransfer1);
        jumtransfer1.setBounds(0, 0, 6, 20);
        panel1.add(norek);
        norek.setBounds(260, 170, 200, 40);
        panel1.add(jumtransfer2);
        jumtransfer2.setBounds(260, 270, 200, 40);

        getContentPane().add(panel1);
        panel1.setBounds(10, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TransaksiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiBtnActionPerformed
        // TODO add your handling code here:
        new Atm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TransaksiBtnActionPerformed

    private void TransaksiBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiBtn1ActionPerformed
        // TODO add your handling code here:
        TransferModel tf = new TransferModel();
        InformasiSaldoModel saldo = new InformasiSaldoModel();
        String jmlh = norek.getText();
        double jmlh2 = Double.parseDouble(jmlh);
        tf.transfer = jmlh2;
        double s =  Double.parseDouble(saldo.getSaldo());
        double hasil = s- tf.transfer;
        if(tf != null){
            sisa.setVisible(true);
            sisa.setText("SISA SALDO ANDA : Rp "+hasil);
        }else{
            sisa.setVisible(false);}
    }//GEN-LAST:event_TransaksiBtn1ActionPerformed

    private void jumtransfer1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jumtransfer1InputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jumtransfer1InputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TransaksiBtn;
    private javax.swing.JButton TransaksiBtn1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jumtransfer1;
    private javax.swing.JTextField jumtransfer2;
    private javax.swing.JTextField norek;
    private java.awt.Panel panel1;
    private javax.swing.JLabel sisa;
    // End of variables declaration//GEN-END:variables
}
